- name: Configure Firewall
  hosts: servers
  become: true

  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        port: 22

    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80

    - name: Enable UFW
      ufw:
        state: enabled